version: "3.8"

services:
  app:
    container_name: sync-manager-app
    build: .
    volumes:
      - ./logs:/logs
      - ./secrets:/secrets
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - db
      - rabbitmq
    restart: on-failure

  db:
    container_name: sync-manager-db
    image: postgres:latest
    user: "postgres:postgres"
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: sync-manager-rabbitmq
    image: rabbitmq:management
    ports:
      - "${AMQP_PORT}:${AMQP_PORT}"
      - "${AMQP_WEB_PORT}:${AMQP_WEB_PORT}"
    env_file:
      - .env
    # healthcheck:
    #   test: ["CMD-SHELL", "rabbitmqctl status | grep -q 'running'"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 5

volumes:
  pg-data:
    driver: local